### PR TITLE
input field must be filled before searching

### PR DESCRIPTION
**Pull request by sakshee-19**
**Checklist**

- [X] My branch is up-to-date with the upstream `develop` branch.
- [ ] I have added necessary documentation (if appropriate).

**Which issue does this PR fix?**: 
fixes: #

**Why do we need this PR?**:
It restricted the irrelevant search of `empty field` in the search bar. It specifies that an input field must be filled out before submitting the form.

If relevant, please include a screenshot.
screenshot from 2018-03-10 10-37-58

### CODE REVIEW

**Comment by sakshee-19** [comment]
@AdiChat @Pl4gue Please approve if required.

**Comment by AdiChat** [comment]
In my opinion, showing a prompt or error for this case will interfere with user experience. Taking no action on empty input seems to be a better option.

**Comment by sakshee-19** [comment]
@AdiChat Please review.

**Comment by AdiChat** [comment]
Nice work :+1:

We must, also, ignore punctuations like `_`, `-`, `/` and others. Kindly consider this as well. :+1:

**Comment by sakshee-19** [comment]
@AdiChat Please review.

**Comment by AdiChat** [comment]
Looks great 😍 

Hope you are enjoying your journey 🚆  with **OpenGenus**

**Pull request merged**
