### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by iattempt**
**Checklist**

- [ ] My branch is up-to-date with the upstream `develop` branch.
- [ ] I have added necessary documentation (if appropriate).

**Which issue does this PR fix?**: 
1. extract methods for controller.
2. Calculator: using Ajax, add memory recall/clear buttons, responsible design.
3. Code: path is not match result, add Github link, typesetting.
4. searchResult: separated/rearrange result templates.

**Why do we need this PR?**:
1. Code is hard to maintain.

**Demo (optional)**:

Some tips for you to write the instructions:
- Prefer bulleted description
- Start after checking out this branch
- Include any setup required, such as migrating databases, etc.

+ Code
Old:
screen shot 2018-05-06 at 9 16 20 am

Now:
screen shot 2018-05-06 at 9 11 08 am

+ Calculator
Old:
screen shot 2018-05-06 at 9 21 40 am
screen shot 2018-05-06 at 9 16 42 am

Now:
screen shot 2018-05-06 at 9 10 01 am
screen shot 2018-05-06 at 9 08 38 am

**Testing instructions:**

If there is any work still left to do, please add it here.

**TODOs (if any)**:
1. code showing can be embedded in result (to be carousal or else).

### CODE REVIEW

**Comment by AdiChat** [comment]
Looks great 😍 

Hope you are enjoying your journey 🚆  with **OpenGenus**
positive_opengenus_major

**Comment by sakshee-19** [comment]
@AdiChat @iattempt Due to changes in `views.py` the functionality of `real-time search suggestion` is removed as the function `search_suggestion` is never being called.

**Comment by sakshee-19** [comment]
Also, it is showing `Template Does not exits` error for each query.

**Comment by iattempt** [comment]
@sakshee-19 thanks for feedback😀.
1. The search_suggestion is already renamed searchSuggestion, please check it again.
2. Please clone the repository again (in another temporary directory), I think it will work well then.

```
mkdir temp
cd temp
git clone https://github.com/OpenGenus/cosmos-search.git
cd cosmos-search
echo cp your .env to here
./scripts/develop.sh
source env/bin/activate
./scripts/develop.sh
```

**Comment by sakshee-19** [comment]
@iattempt  My repository is even with `OpenGenus/cosmos-search` master branch. You need to change `searchResults.html` to `searchresults.html` in `views.py query_get` function .

**Comment by iattempt** [comment]
@sakshee-19 Oh no, It is my bad, because filenames is insensitive in my computer.
IMHO, it should be addressed by changing `searchresults.html` to `searchResults.html` in /search/templates/cosmos, due to the other results' template are named with camelCase.
Could you push an request for this error? I'll back to my secondary military service life😫 soon.

**Pull request merged**
