### PR TITLE
count of solutions

### PR DESCRIPTION
**Pull request by khatryshikha**
**Checklist**

- [x] My branch is up-to-date with the upstream `develop` branch.
- [ ] I have added necessary documentation (if appropriate).

**Which issue does this PR fix?**: 
fixes: #114 
For each search query we get multiple results, for each results we get the list of solutions. If the user can see the count of files for each it would be better as he/she will get more info.

**Why do we need this PR?**:
The PR makes the search queries more informative for the user.

If relevant, please include a screenshot.

### CODE REVIEW

**Comment by khatryshikha** [comment]
@AdiChat please review.

**Comment by vaibhavsingh97** [comment]
@khatryshikha Yes

**Comment by khatryshikha** [comment]
@vaibhavsingh97 please review.

**Comment by AdiChat** [comment]
Looks great. :+1:  You may go for the representation like "1 solution", "10 solutions".

Kindly take a look into it and make appropriate changes. :+1:

**Comment by khatryshikha** [comment]
countchanged

@AdiChat please review.

**Comment by AdiChat** [comment]
Looks great 😍 

Hope you are enjoying your journey 🚆  with **OpenGenus**

positive_opengenus

**Comment by khatryshikha** [comment]
Thank you so much @AdiChat .

**Comment by khatryshikha** [comment]
Thank you @AdiChat. :-) Looking forward to work more with OpenGenus.

**Pull request merged**
